name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            build-essential \
            git \
            openjdk-8-jdk \
            unzip \
            zip \
            python3-pip \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev
            
    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.33
        
    - name: Create basic buildozer.spec
      run: |
        cat > buildozer.spec << 'EOF'
[app]
title = My App
package.name = myapp
package.domain = org.test

version = 0.1
requirements = python3

[buildozer]
log_level = 2

[android]
api = 28
minapi = 21
ndk = 19c
EOF
        
    - name: Build APK
      run: |
        buildozer -v android debug
        
    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: bin/*.apk
