name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip git
        
    - name: Install Buildozer with Cython
      run: |
        pip install buildozer cython==0.29.33
        
    - name: Create buildozer.spec
      run: |
        buildozer init
        # Ждем немного
        sleep 5
        
    - name: Build APK
      run: |
        buildozer -v android debug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: nvweb-app
        path: bin/*.apk
