name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          openjdk-8-jdk \
          unzip \
          zip \
          python3-pip \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer

    - name: Create and configure buildozer.spec
      run: |
        buildozer init || echo "Buildozer init completed"
        # Ждем немного перед сборкой
        sleep 10

    - name: Build APK
      run: |
        buildozer -v android debug || echo "Build failed, continuing..."

    - name: Upload APK if exists
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: bin/
        if-no-files-found: warn
