name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            build-essential \
            git \
            openjdk-11-jdk \
            unzip \
            zip \
            python3-pip \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            cmake \
            libffi-dev \
            libssl-dev
            
    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.33
        
    - name: Create buildozer.spec
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
          echo "Created buildozer.spec"
        else
          echo "buildozer.spec already exists"
        fi
        
    - name: Build APK
      run: |
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: bin/*.apk
        retention-days: 7
